// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hero struct {
	ID          string `json:"id"`
	NamaHero    string `json:"nama_hero"`
	Role        string `json:"role"`
	Emblem      string `json:"emblem"`
	BattleSpell string `json:"battle_spell"`
}

type HeroInput struct {
	NamaHero    string `json:"nama_hero"`
	Role        string `json:"role"`
	Emblem      string `json:"emblem"`
	BattleSpell string `json:"battle_spell"`
}
